In [38]:
# Imports
import pandas as pd
import numpy as np
from tools import process
from tools import filter

In [39]:
# Processed data to be used
df = pd.read_csv("files/data.csv")
df_array = df.to_numpy()
df_array = process.array(df_array)
print(df_array)

[[ 0  5  1  0 11  0  1  4  0  1  7  0  3  2  0]
 [ 1  5  2  2 12  0  1  5  0  0  5  0  1  2  0]]


In [42]:
df_array = filter.qt(df_array)

In [43]:
print(df_array)

[[ 0  5  1  0 11  0  1  4  0  1  7  0  3  2  0]
 [ 1  5  2  2 12  0  1  5  0  0  5  0  1  2  0]]
